version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: task_manager_db
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task_manager_network

  app:
    image: openjdk:17
    container_name: task_manager_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/task_manager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: default
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - task_manager_network

volumes:
  postgres_data:

networks:
  task_manager_network:
    driver: bridge
