spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: default
  jwt:
    secret: 0b0e622756ab3aeb3d935ccd3410bb226675ea121eabecbc761790fb9655e0c8

